services:

  postgres:
    image: postgres:13
    container_name: airflow-postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db:/var/lib/postgresql/data

  mysql:
    image: mysql:8.0
    container_name: airflow-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
    ports:
      - "3306:3306"
    volumes:
      - mysql-db:/var/lib/mysql

  spark:
    image: bitnami/spark:3.5
    container_name: airflow-spark
    environment:
      - SPARK_MODE=master
    ports:
      - "8081:8080"

  git-sync:
    image: registry.k8s.io/git-sync/git-sync:v4.0.0
    container_name: airflow-gitsync
    user: "0:0"
    volumes:
      - dags:/git
    environment:
      GITSYNC_REPO: https://github.com/sultanlodh/airflowrepo.git
      GITSYNC_REF: UAT
      GITSYNC_ROOT: /git
      GITSYNC_LINK: repo
      GITSYNC_PERIOD: 60s

  airflow-webserver:
    build: .
    container_name: airflow-webserver
    depends_on:
      - postgres
      - git-sync
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      PYTHONPATH: /opt/airflow/dags/repo/airflow
    ports:
      - "8080:8080"
    volumes:
      - dags:/opt/airflow/dags
      - ./dbt:/opt/dbt

  airflow-scheduler:
    build: .
    container_name: airflow-scheduler
    depends_on:
      - postgres
      - git-sync
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      PYTHONPATH: /opt/airflow/dags/repo/airflow
    volumes:
      - dags:/opt/airflow/dags
      - ./dbt:/opt/dbt

volumes:
  postgres-db:
  mysql-db:
  dags: