x-airflow-common: &airflow-common
  build: .
  environment:
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags/repo/airflow/dag
  volumes:
    - dags:/opt/airflow/dags
  depends_on:
    - postgres

services:

  postgres:
    image: postgres:13
    container_name: airflow-postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db:/var/lib/postgresql/data

  airflow-init:
    <<: *airflow-common
    container_name: airflow-init
    command: >
      bash -c "
      airflow db migrate &&
      airflow users create
      --username airflow
      --password airflow
      --firstname admin
      --lastname user
      --role Admin
      --email admin@example.com
      "

  airflow-webserver:
    <<: *airflow-common
    container_name: airflow-webserver
    ports:
      - "8080:8080"
    command: webserver

  airflow-scheduler:
    <<: *airflow-common
    container_name: airflow-scheduler
    command: scheduler

  git-sync:
    image: registry.k8s.io/git-sync/git-sync:v4.0.0
    container_name: airflow-gitsync
    user: "0:0"
    volumes:
      - dags:/git
    environment:
      GITSYNC_REPO: https://github.com/sultanlodh/airflowrepo.git
      GITSYNC_REF: main
      GITSYNC_ROOT: /git
      GITSYNC_LINK: repo
      GITSYNC_PERIOD: 60s
      GITSYNC_ONE_TIME: "false"

volumes:
  postgres-db:
  dags: